/******************************************************************************/
/*                 Generated by IBExpert 03/02/2025 17:02:52                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE EXTEND_ORDERMSERVICO (
    ID                DOM_INTEGER NOT NULL /* DOM_INTEGER = INTEGER */,
    CD_EMPRESA        DOM_INTEGER NOT NULL /* DOM_INTEGER = INTEGER */,
    NR_ORDERMSERVICO  DOM_INTEGER NOT NULL /* DOM_INTEGER = INTEGER */,
    CD_ITEM           DOM_INTEGER NOT NULL /* DOM_INTEGER = INTEGER */,
    DS_ITEM           DOM_VARCHAR500 NOT NULL /* DOM_VARCHAR500 = VARCHAR(500) */,
    CD_VENDEDOR       DOM_INTEGER /* DOM_INTEGER = INTEGER */,
    CD_CLIENTE        DOM_INTEGER /* DOM_INTEGER = INTEGER */,
    QT_PEDIDA         DOM_NUMERIC15_2 /* DOM_NUMERIC15_2 = NUMERIC(15,2) */,
    PS_PEDIDO         DOM_NUMERIC15_2 /* DOM_NUMERIC15_2 = NUMERIC(15,2) */,
    NM_SEPARADOR      DOM_VARCHAR30 /* DOM_VARCHAR30 = VARCHAR(30) */,
    STATUS            DOM_CHAR1 DEFAULT 'I' /* DOM_CHAR1 = CHAR(1) */ /* DOM_CHAR1 = CHAR(1) */ /* DOM_CHAR1 = CHAR(1) */,
    DT_INICIO         DOM_TIMESTAMP /* DOM_TIMESTAMP = TIMESTAMP */,
    DT_FIM            DOM_TIMESTAMP /* DOM_TIMESTAMP = TIMESTAMP */
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE EXTEND_ORDERMSERVICO ADD CONSTRAINT PK_EXTEND_ORDERMSERVICO PRIMARY KEY (ID, CD_EMPRESA, NR_ORDERMSERVICO, CD_ITEM);


/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
