/******************************************************************************/
/****              Generated by IBExpert 18/02/2025 08:49:14               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE EXTEND_SEPARACAO (
    CD_EMPRESA      INTEGER NOT NULL,
    NR_PEDIDO       INTEGER NOT NULL,
    NM_USUARIO      VARCHAR(50) NOT NULL,
    STATUS          CHAR(1),
    DT_INICIO       TIMESTAMP,
    DT_FIM          TIMESTAMP,
    DTFIM_CONF      DOM_TIMESTAMP /* DOM_TIMESTAMP = TIMESTAMP */,
    DTFIM_FAT       DOM_TIMESTAMP /* DOM_TIMESTAMP = TIMESTAMP */,
    NM_CONFERIDOR   DOM_VARCHAR5 /* DOM_VARCHAR5 = VARCHAR(5) */,
    NM_ESTOQUISTA   DOM_VARCHAR30 /* DOM_VARCHAR30 = VARCHAR(30) */,
    DS_DIVERGENCIA  DOM_VARCHAR5000 /* DOM_VARCHAR5000 = VARCHAR(5000) */
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE EXTEND_SEPARACAO ADD CONSTRAINT PK_EXTEND_SEPARACAO PRIMARY KEY (CD_EMPRESA, NR_PEDIDO);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON EXTEND_SEPARACAO TO USER BELENZIER01;
GRANT ALL ON EXTEND_SEPARACAO TO USER USER01;