SET TERM ^ ;

CREATE OR ALTER PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO (
    I_CD_EMPRESA INTEGER)
RETURNS (
    TIPO_TABLE DOM_CHAR1,
    STATUS DOM_CHAR1,
    CD_EMPRESA DOM_INTEGER,
    CD_ITEM DOM_INTEGER,
    DESCR DOM_VARCHAR100,
    LOCALS DOM_VARCHAR100,
    CD_PESSOA DOM_INTEGER,
    CD_VENDEDOR DOM_INTEGER,
    SG_UNIDMED DOM_VARCHAR10,
    DS_MARCA DOM_VARCHAR100,
    NR_ORDEMSERVICO DOM_INTEGER,
    NM_CLIENTE DOM_VARCHAR100,
    NM_VENDEDOR DOM_VARCHAR100,
    DS_ITEM DOM_VARCHAR100,
    QNT DOM_NUMERIC15_2,
    NM_SEPARADOR DOM_VARCHAR100,
    ID DOM_INTEGER,
    CD_FORNECEDOR1 DOM_VARCHAR120)
AS
BEGIN
  FOR
    SELECT
        TIPO_TABLE, STATUS, CD_EMPRESA, CD_ITEM,
        DESCR, LOCALS, CD_PESSOA, CD_VENDEDOR, SG_UNIDMED,
        DS_MARCA, NR_ORDEMSERVICO, NM_CLIENTE, NM_VENDEDOR,
        DS_ITEM, QNT, NM_SEPARADOR, ID, CD_FORNECEDOR1
        FROM (
            WITH SERVICOCALCULADO AS (
                SELECT
                    SI.CD_EMPRESA,
                    SI.NR_ORDEMSERVICO,
                    SI.CD_ITEM,
                    MAX(COALESCE(SI.PS_SERVICOITEM, SI.QT_SERVICOITEM)) AS QT_SOLICITADA,
                    SUM(COALESCE(EO.PS_PEDIDO, EO.QT_PEDIDA, 0)) AS QT_PEDIDA_E
                FROM SERVICOITEM SI
                LEFT JOIN EXTEND_ORDERMSERVICO EO 
                    ON EO.CD_EMPRESA = SI.CD_EMPRESA 
                    AND EO.NR_ORDERMSERVICO = SI.NR_ORDEMSERVICO 
                    AND EO.CD_ITEM = SI.CD_ITEM
                WHERE SI.DT_REGISTRO BETWEEN CURRENT_TIMESTAMP-2 AND CURRENT_TIMESTAMP+1
                    AND SI.CD_EMPRESA = :I_CD_EMPRESA
                GROUP BY SI.CD_EMPRESA, SI.NR_ORDEMSERVICO, SI.CD_ITEM
                HAVING MAX(COALESCE(SI.PS_SERVICOITEM, SI.QT_SERVICOITEM)) >= SUM(COALESCE(EO.PS_PEDIDO, EO.QT_PEDIDA, 0))
            )
            SELECT
                'O' TIPO_TABLE,
                COALESCE(EO.STATUS, 'N') STATUS,
                OS.CD_EMPRESA, SI.CD_ITEM, I.DS_ITEM DESCR, LIST(LE.DS_LOCAL, ',') LOCALS,
                OS.CD_PESSOA, SI.CD_VENDEDOR, I.SG_UNIDMED, M.DS_MARCA,
                OS.NR_ORDEMSERVICO, PC.NM_PESSOA NM_CLIENTE,
                PV.NM_PESSOA NM_VENDEDOR,
                SI.CD_ITEM||' - '||I.DS_ITEM||' ('||LIST(LE.DS_LOCAL, ', ')||')' DS_ITEM,
                CAST(COALESCE(EO.PS_PEDIDO, EO.QT_PEDIDA, SI.PS_SERVICOITEM, SI.QT_SERVICOITEM)AS NUMERIC(15, 2)) QNT,
                COALESCE(EO.NM_SEPARADOR, '') NM_SEPARADOR,
                COALESCE(EO.ID, 1) ID, I.CD_FORNECEDOR1
            FROM ORDEMSERVICO OS
            INNER JOIN SERVICOITEM SI ON (SI.CD_EMPRESA = OS.CD_EMPRESA
                AND SI.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO)
            INNER JOIN PESSOA PC ON (PC.CD_PESSOA = OS.CD_PESSOA)
            INNER JOIN PESSOA PV ON (PV.CD_PESSOA = SI.CD_VENDEDOR)
            INNER JOIN ITEM I ON (I.CD_ITEM = SI.CD_ITEM)
            INNER JOIN ITEMLOCAL IL ON (IL.CD_ITEM = I.CD_ITEM
                AND IL.CD_TIPOLOCAL = CASE :I_CD_EMPRESA
                                        WHEN 7 THEN 7
                                        WHEN 40 THEN 1
                                        WHEN 50 THEN 2
                                        WHEN 60 THEN 3
                                        END)
            INNER JOIN LOCALESTOQUE LE ON (LE.CD_TIPOLOCAL = IL.CD_TIPOLOCAL
                AND LE.CD_LOCAL = IL.CD_LOCAL)
            LEFT JOIN EXTEND_ORDERMSERVICO EO ON (EO.CD_EMPRESA = SI.CD_EMPRESA
                AND EO.NR_ORDERMSERVICO = SI.NR_ORDEMSERVICO
                AND EO.CD_ITEM = SI.CD_ITEM)
            LEFT JOIN ITEMCONFERENCIAORDEM ICO ON (ICO.CD_EMPRESA = OS.CD_EMPRESA
                AND ICO.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO
                AND ICO.CD_ITEM = SI.CD_ITEM)
            INNER JOIN MARCA M ON (M.CD_MARCA = I.CD_MARCA)
            LEFT JOIN ITEMREQUISICAOOFICINA IRQ ON (IRQ.CD_EMPRESAOS = OS.CD_EMPRESA
                    AND IRQ.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO
                    AND IRQ.CD_ITEM = SI.CD_ITEM)
            WHERE OS.ST_ORDEMSERVICO = 'A'
                AND OS.CD_EMPRESA IN (:I_CD_EMPRESA)
                AND ICO.NR_ORDEMSERVICO IS NULL
                AND COALESCE(EO.STATUS, 'I') NOT IN ('F')
                AND OS.DT_EMISSAO >= CURRENT_DATE - 30
                AND IRQ.CD_EMPRESA IS NULL
            GROUP BY
                TIPO_TABLE, STATUS, CD_EMPRESA,
                CD_ITEM, CD_PESSOA, CD_VENDEDOR,
                NR_ORDEMSERVICO, NM_CLIENTE, NM_VENDEDOR, I.CD_FORNECEDOR1,
                SI.CD_ITEM,I.DS_ITEM, QNT, NM_SEPARADOR, ID, M.DS_MARCA, I.SG_UNIDMED
            
            UNION ALL
            
            SELECT
                'O' AS TIPO_TABLE,
                'N' AS STATUS,
                OS.CD_EMPRESA,
                SI.CD_ITEM,
                I.DS_ITEM AS DESCR,
                LIST(LE.DS_LOCAL, ', ') AS LOCALS,
                OS.CD_PESSOA,
                SI.CD_VENDEDOR,
                I.SG_UNIDMED,
                M.DS_MARCA,
                OS.NR_ORDEMSERVICO,
                PC.NM_PESSOA AS NM_CLIENTE,
                PV.NM_PESSOA AS NM_VENDEDOR,
                SI.CD_ITEM || ' - ' || I.DS_ITEM || ' (' || LIST(LE.DS_LOCAL, ', ') || ')' AS DS_ITEM,
                CAST(QT_SOLICITADA - QT_PEDIDA_E AS NUMERIC(15, 2)) AS QNT,
                '' AS NM_SEPARADOR,
                MAX(COALESCE(EO.ID, 0)) + 1 ID,
                I.CD_FORNECEDOR1
            FROM ORDEMSERVICO OS
            INNER JOIN SERVICOITEM SI 
                ON SI.CD_EMPRESA = OS.CD_EMPRESA 
                AND SI.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO
            INNER JOIN PESSOA PC ON PC.CD_PESSOA = OS.CD_PESSOA
            INNER JOIN PESSOA PV ON PV.CD_PESSOA = SI.CD_VENDEDOR
            INNER JOIN ITEM I ON I.CD_ITEM = SI.CD_ITEM
            INNER JOIN ITEMLOCAL IL 
                ON IL.CD_ITEM = I.CD_ITEM
                AND IL.CD_TIPOLOCAL = CASE :I_CD_EMPRESA
                                        WHEN 7 THEN 7
                                        WHEN 40 THEN 1
                                        WHEN 50 THEN 2
                                        WHEN 60 THEN 3
                                      END
            INNER JOIN LOCALESTOQUE LE 
                ON LE.CD_TIPOLOCAL = IL.CD_TIPOLOCAL
                AND LE.CD_LOCAL = IL.CD_LOCAL
            LEFT JOIN EXTEND_ORDERMSERVICO EO 
                ON EO.CD_EMPRESA = SI.CD_EMPRESA 
                AND EO.NR_ORDERMSERVICO = SI.NR_ORDEMSERVICO 
                AND EO.CD_ITEM = SI.CD_ITEM
            LEFT JOIN ITEMCONFERENCIAORDEM ICO 
                ON ICO.CD_EMPRESA = OS.CD_EMPRESA 
                AND ICO.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO 
                AND ICO.CD_ITEM = SI.CD_ITEM
            INNER JOIN MARCA M ON M.CD_MARCA = I.CD_MARCA
            LEFT JOIN ITEMREQUISICAOOFICINA IRQ 
                ON IRQ.CD_EMPRESAOS = OS.CD_EMPRESA 
                AND IRQ.NR_ORDEMSERVICO = OS.NR_ORDEMSERVICO 
                AND IRQ.CD_ITEM = SI.CD_ITEM
            INNER JOIN SERVICOCALCULADO SC 
                ON SC.CD_EMPRESA = SI.CD_EMPRESA
                AND SC.NR_ORDEMSERVICO = SI.NR_ORDEMSERVICO 
                AND SC.CD_ITEM = SI.CD_ITEM
            WHERE OS.ST_ORDEMSERVICO = 'A'
                AND OS.CD_EMPRESA IN (:I_CD_EMPRESA)
                AND COALESCE(EO.STATUS, 'N') IN ('I', 'F')
                AND OS.DT_EMISSAO >= CURRENT_DATE - 30
                AND IRQ.CD_EMPRESA IS NULL
            GROUP BY
                TIPO_TABLE, STATUS, CD_EMPRESA, CD_ITEM, DESCR,
                CD_PESSOA, CD_VENDEDOR, SG_UNIDMED, DS_MARCA,
                NR_ORDEMSERVICO, NM_CLIENTE, NM_VENDEDOR, QNT,
                NM_SEPARADOR, CD_FORNECEDOR1, SC.QT_SOLICITADA, SC.QT_PEDIDA_E
            HAVING SC.QT_SOLICITADA <> SC.QT_PEDIDA_E
        )Y
    ORDER BY Y.CD_EMPRESA, Y.NR_ORDEMSERVICO
    INTO :TIPO_TABLE, :STATUS, :CD_EMPRESA, :CD_ITEM,
         :DESCR, :LOCALS, :CD_PESSOA, :CD_VENDEDOR,
         :SG_UNIDMED, :DS_MARCA, :NR_ORDEMSERVICO,
         :NM_CLIENTE, :NM_VENDEDOR, :DS_ITEM,
         :QNT, :NM_SEPARADOR, :ID, :CD_FORNECEDOR1
  DO
  BEGIN
    SUSPEND;
  END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON SERVICOITEM TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON EXTEND_ORDERMSERVICO TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON ORDEMSERVICO TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON PESSOA TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON ITEM TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON ITEMLOCAL TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON LOCALESTOQUE TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON ITEMCONFERENCIAORDEM TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON MARCA TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;
GRANT SELECT ON ITEMREQUISICAOOFICINA TO PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE EXTEND_ORDEMSERVICO_SEPARACAO TO SYSDBA;